<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CdtCatalog;

class CdtCatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Creando catálogo CDT...');

        $procedures = [
            // Procedimientos Preventivos
            [
                'cdt_code' => 'D1110',
                'category' => 'Preventivo',
                'subcategory' => 'Profilaxis',
                'procedure_name' => 'Profilaxis Dental',
                'description' => 'Limpieza dental profesional para remover placa y sarro',
                'clinical_notes' => 'Procedimiento de rutina para mantenimiento de salud oral',
                'base_price' => 800.00,
                'estimated_duration' => 60,
                'difficulty_level' => 'basic',
                'required_materials' => ['Cepillo profiláctico', 'Pasta profiláctica', 'Hilo dental'],
                'contraindications' => ['Enfermedad periodontal avanzada'],
                'requires_anesthesia' => false,
                'is_surgical' => false,
                'is_active' => true,
            ],
            [
                'cdt_code' => 'D1120',
                'category' => 'Preventivo',
                'subcategory' => 'Profilaxis',
                'procedure_name' => 'Profilaxis Dental con Fluoruro',
                'description' => 'Limpieza dental con aplicación de fluoruro',
                'clinical_notes' => 'Incluye aplicación tópica de fluoruro para fortalecimiento',
                'base_price' => 1000.00,
                'estimated_duration' => 75,
                'difficulty_level' => 'basic',
                'required_materials' => ['Cepillo profiláctico', 'Pasta profiláctica', 'Fluoruro tópico'],
                'contraindications' => ['Alergia al fluoruro'],
                'requires_anesthesia' => false,
                'is_surgical' => false,
                'is_active' => true,
            ],

            // Restauraciones
            [
                'cdt_code' => 'D2140',
                'category' => 'Restaurativo',
                'subcategory' => 'Amalgama',
                'procedure_name' => 'Restauración de Amalgama - Una Superficie',
                'description' => 'Restauración con amalgama de plata en una superficie',
                'clinical_notes' => 'Restauración directa con amalgama de plata',
                'base_price' => 1200.00,
                'estimated_duration' => 45,
                'difficulty_level' => 'intermediate',
                'required_materials' => ['Amalgama de plata', 'Matriz', 'Cemento de ionómero'],
                'contraindications' => ['Alergia a metales'],
                'requires_anesthesia' => true,
                'is_surgical' => false,
                'is_active' => true,
            ],
            [
                'cdt_code' => 'D2150',
                'category' => 'Restaurativo',
                'subcategory' => 'Amalgama',
                'procedure_name' => 'Restauración de Amalgama - Dos Superficies',
                'description' => 'Restauración con amalgama de plata en dos superficies',
                'clinical_notes' => 'Restauración directa con amalgama de plata',
                'base_price' => 1500.00,
                'estimated_duration' => 60,
                'difficulty_level' => 'intermediate',
                'required_materials' => ['Amalgama de plata', 'Matriz', 'Cemento de ionómero'],
                'contraindications' => ['Alergia a metales'],
                'requires_anesthesia' => true,
                'is_surgical' => false,
                'is_active' => true,
            ],
            [
                'cdt_code' => 'D2391',
                'category' => 'Restaurativo',
                'subcategory' => 'Resina',
                'procedure_name' => 'Restauración de Resina - Una Superficie',
                'description' => 'Restauración estética con resina compuesta',
                'clinical_notes' => 'Restauración directa con resina compuesta',
                'base_price' => 1800.00,
                'estimated_duration' => 60,
                'difficulty_level' => 'intermediate',
                'required_materials' => ['Resina compuesta', 'Adhesivo', 'Lámpara de curado'],
                'contraindications' => ['Alergia a resinas'],
                'requires_anesthesia' => true,
                'is_surgical' => false,
                'is_active' => true,
            ],
            [
                'cdt_code' => 'D2392',
                'category' => 'Restaurativo',
                'subcategory' => 'Resina',
                'procedure_name' => 'Restauración de Resina - Dos Superficies',
                'description' => 'Restauración estética con resina compuesta',
                'clinical_notes' => 'Restauración directa con resina compuesta',
                'base_price' => 2200.00,
                'estimated_duration' => 75,
                'difficulty_level' => 'intermediate',
                'required_materials' => ['Resina compuesta', 'Adhesivo', 'Lámpara de curado'],
                'contraindications' => ['Alergia a resinas'],
                'requires_anesthesia' => true,
                'is_surgical' => false,
                'is_active' => true,
            ],

            // Endodoncia
            [
                'cdt_code' => 'D3310',
                'category' => 'Endodoncia',
                'subcategory' => 'Tratamiento de Conducto',
                'procedure_name' => 'Tratamiento de Conducto - Anterior',
                'description' => 'Tratamiento de conducto radicular en diente anterior',
                'clinical_notes' => 'Tratamiento endodóntico completo con obturación',
                'base_price' => 3500.00,
                'estimated_duration' => 120,
                'difficulty_level' => 'advanced',
                'required_materials' => ['Limas endodónticas', 'Gutapercha', 'Cemento endodóntico'],
                'contraindications' => ['Diente no restaurable'],
                'requires_anesthesia' => true,
                'is_surgical' => false,
                'is_active' => true,
            ],
            [
                'cdt_code' => 'D3320',
                'category' => 'Endodoncia',
                'subcategory' => 'Tratamiento de Conducto',
                'procedure_name' => 'Tratamiento de Conducto - Premolar',
                'description' => 'Tratamiento de conducto radicular en premolar',
                'clinical_notes' => 'Tratamiento endodóntico completo con obturación',
                'base_price' => 4000.00,
                'estimated_duration' => 150,
                'difficulty_level' => 'advanced',
                'required_materials' => ['Limas endodónticas', 'Gutapercha', 'Cemento endodóntico'],
                'contraindications' => ['Diente no restaurable'],
                'requires_anesthesia' => true,
                'is_surgical' => false,
                'is_active' => true,
            ],
            [
                'cdt_code' => 'D3330',
                'category' => 'Endodoncia',
                'subcategory' => 'Tratamiento de Conducto',
                'procedure_name' => 'Tratamiento de Conducto - Molar',
                'description' => 'Tratamiento de conducto radicular en molar',
                'clinical_notes' => 'Tratamiento endodóntico completo con obturación',
                'base_price' => 4500.00,
                'estimated_duration' => 180,
                'difficulty_level' => 'advanced',
                'required_materials' => ['Limas endodónticas', 'Gutapercha', 'Cemento endodóntico'],
                'contraindications' => ['Diente no restaurable'],
                'requires_anesthesia' => true,
                'is_surgical' => false,
                'is_active' => true,
            ],

            // Cirugía Oral
            [
                'cdt_code' => 'D7210',
                'category' => 'Cirugía Oral',
                'subcategory' => 'Extracciones',
                'procedure_name' => 'Extracción Simple',
                'description' => 'Extracción de diente con fórceps',
                'clinical_notes' => 'Extracción simple sin elevación de colgajo',
                'base_price' => 1500.00,
                'estimated_duration' => 30,
                'difficulty_level' => 'intermediate',
                'required_materials' => ['Fórceps', 'Elevador', 'Gasas', 'Suturas'],
                'contraindications' => ['Trastornos de coagulación'],
                'requires_anesthesia' => true,
                'is_surgical' => true,
                'is_active' => true,
            ],
            [
                'cdt_code' => 'D7220',
                'category' => 'Cirugía Oral',
                'subcategory' => 'Extracciones',
                'procedure_name' => 'Extracción Quirúrgica',
                'description' => 'Extracción quirúrgica con elevación de colgajo',
                'clinical_notes' => 'Extracción quirúrgica con elevación de colgajo y sutura',
                'base_price' => 2500.00,
                'estimated_duration' => 60,
                'difficulty_level' => 'advanced',
                'required_materials' => ['Fórceps', 'Elevador', 'Bisturí', 'Suturas'],
                'contraindications' => ['Trastornos de coagulación'],
                'requires_anesthesia' => true,
                'is_surgical' => true,
                'is_active' => true,
            ],

            // Prótesis
            [
                'cdt_code' => 'D2740',
                'category' => 'Prótesis',
                'subcategory' => 'Coronas',
                'procedure_name' => 'Corona de Porcelana',
                'description' => 'Corona de porcelana fundida sobre metal',
                'clinical_notes' => 'Corona estética de porcelana sobre estructura metálica',
                'base_price' => 8000.00,
                'estimated_duration' => 120,
                'difficulty_level' => 'advanced',
                'required_materials' => ['Porcelana', 'Metal', 'Cemento dental'],
                'contraindications' => ['Bruxismo severo'],
                'requires_anesthesia' => true,
                'is_surgical' => false,
                'is_active' => true,
            ],
            [
                'cdt_code' => 'D6240',
                'category' => 'Prótesis',
                'subcategory' => 'Puentes',
                'procedure_name' => 'Puente de Porcelana',
                'description' => 'Puente fijo de porcelana',
                'clinical_notes' => 'Puente fijo de porcelana fundida sobre metal',
                'base_price' => 15000.00,
                'estimated_duration' => 180,
                'difficulty_level' => 'advanced',
                'required_materials' => ['Porcelana', 'Metal', 'Cemento dental'],
                'contraindications' => ['Bruxismo severo'],
                'requires_anesthesia' => true,
                'is_surgical' => false,
                'is_active' => true,
            ],

            // Implantes
            [
                'cdt_code' => 'D6010',
                'category' => 'Implantes',
                'subcategory' => 'Colocación',
                'procedure_name' => 'Colocación de Implante',
                'description' => 'Colocación quirúrgica de implante dental',
                'clinical_notes' => 'Colocación quirúrgica de implante de titanio',
                'base_price' => 12000.00,
                'estimated_duration' => 120,
                'difficulty_level' => 'advanced',
                'required_materials' => ['Implante de titanio', 'Bisturí', 'Suturas'],
                'contraindications' => ['Enfermedad periodontal activa'],
                'requires_anesthesia' => true,
                'is_surgical' => true,
                'is_active' => true,
            ],
            [
                'cdt_code' => 'D6056',
                'category' => 'Implantes',
                'subcategory' => 'Prótesis',
                'procedure_name' => 'Corona sobre Implante',
                'description' => 'Corona de porcelana sobre implante',
                'clinical_notes' => 'Corona estética sobre implante dental',
                'base_price' => 10000.00,
                'estimated_duration' => 90,
                'difficulty_level' => 'advanced',
                'required_materials' => ['Porcelana', 'Pilar de implante', 'Cemento dental'],
                'contraindications' => ['Fallo de osteointegración'],
                'requires_anesthesia' => false,
                'is_surgical' => false,
                'is_active' => true,
            ],

            // Ortodoncia
            [
                'cdt_code' => 'D8080',
                'category' => 'Ortodoncia',
                'subcategory' => 'Brackets',
                'procedure_name' => 'Colocación de Brackets',
                'description' => 'Colocación de aparato ortodóntico fijo',
                'clinical_notes' => 'Colocación de brackets metálicos',
                'base_price' => 5000.00,
                'estimated_duration' => 120,
                'difficulty_level' => 'advanced',
                'required_materials' => ['Brackets', 'Arcos', 'Ligaduras'],
                'contraindications' => ['Enfermedad periodontal activa'],
                'requires_anesthesia' => false,
                'is_surgical' => false,
                'is_active' => true,
            ],
            [
                'cdt_code' => 'D8090',
                'category' => 'Ortodoncia',
                'subcategory' => 'Mantenimiento',
                'procedure_name' => 'Ajuste Ortodóntico',
                'description' => 'Ajuste de aparato ortodóntico',
                'clinical_notes' => 'Ajuste mensual de aparato ortodóntico',
                'base_price' => 800.00,
                'estimated_duration' => 30,
                'difficulty_level' => 'intermediate',
                'required_materials' => ['Arcos', 'Ligaduras', 'Elásticos'],
                'contraindications' => ['Enfermedad periodontal activa'],
                'requires_anesthesia' => false,
                'is_surgical' => false,
                'is_active' => true,
            ],

            // Periodoncia
            [
                'cdt_code' => 'D4341',
                'category' => 'Periodoncia',
                'subcategory' => 'Raspaje',
                'procedure_name' => 'Raspaje y Alisado Radicular',
                'description' => 'Tratamiento de enfermedad periodontal',
                'clinical_notes' => 'Raspaje y alisado radicular por cuadrante',
                'base_price' => 2000.00,
                'estimated_duration' => 90,
                'difficulty_level' => 'advanced',
                'required_materials' => ['Curetas', 'Ultrasonido', 'Antiséptico'],
                'contraindications' => ['Enfermedad cardíaca'],
                'requires_anesthesia' => true,
                'is_surgical' => false,
                'is_active' => true,
            ],
        ];

        foreach ($procedures as $procedure) {
            CdtCatalog::updateOrCreate(
                ['cdt_code' => $procedure['cdt_code']],
                $procedure
            );
        }

        $this->command->info('✅ Catálogo CDT creado exitosamente:');
        $this->command->info('- 20 procedimientos dentales');
        $this->command->info('- Categorías: Preventivo, Restaurativo, Endodoncia, Cirugía, Prótesis, Implantes, Ortodoncia, Periodoncia');
        $this->command->info('- Precios y duraciones realistas');
    }
}