@extends('layouts.master')

@section('title', 'Nueva factura')

@section('content')
    <div class="row"><div class="col-12"><div class="page-title-box d-flex align-items-center justify-content-between"><div><h4 class="mb-2">Nueva factura</h4><p class="text-muted mb-3">Crea una factura en borrador antes de enviarla o registrar pagos.</p></div><a class="btn btn-light" href="{{ route('billing.index') }}"><i class="fas fa-arrow-left me-1"></i> Volver</a></div></div></div>
    @if($errors->any())<div class="alert alert-danger"><i class="fas fa-exclamation-circle me-2"></i>Revisa los campos marcados antes de guardar.</div>@endif
    <form method="POST" action="{{ route('billing.store') }}">@csrf
        <div class="row">
            <div class="col-xl-8"><div class="card"><div class="card-header"><div class="card-icon"><i class="fas fa-list fs-14 text-muted"></i></div><h4 class="card-title mb-0">Concepto facturado</h4></div><div class="card-body"><div class="row g-3"><div class="col-md-7"><label class="form-label">Procedimiento</label><select class="form-select" name="items[0][cdt_catalog_id]" required><option value="">Seleccione</option>@foreach($cdtCatalog as $item)<option value="{{ $item->id }}" {{ old('items.0.cdt_catalog_id') == $item->id ? 'selected' : '' }}>{{ $item->cdt_code }} — {{ $item->procedure_name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Cantidad</label><input class="form-control" type="number" min="1" name="items[0][quantity]" value="{{ old('items.0.quantity', 1) }}" required></div><div class="col-md-3"><label class="form-label">Precio</label><input class="form-control" type="number" min="0" step="0.01" name="items[0][unit_price]" value="{{ old('items.0.unit_price', 0) }}" required></div></div><p class="small text-muted mt-3 mb-0"><i class="fas fa-info-circle me-1"></i>El procedimiento y su importe quedarán registrados en la factura.</p></div></div></div>
            <div class="col-xl-4"><div class="card"><div class="card-header"><h4 class="card-title mb-0">Datos generales</h4></div><div class="card-body"><div class="mb-3"><label class="form-label">Paciente</label><select class="form-select" name="patient_id" required><option value="">Seleccione</option>@foreach($patients as $patient)<option value="{{ $patient->id }}" {{ old('patient_id') == $patient->id ? 'selected' : '' }}>{{ $patient->patient_code }} — {{ $patient->first_name }} {{ $patient->last_name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Profesional</label><select class="form-select" name="staff_id" required><option value="">Seleccione</option>@foreach($staff as $member)<option value="{{ $member->id }}" {{ old('staff_id') == $member->id ? 'selected' : '' }}>{{ $member->user?->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Fecha</label><input class="form-control" type="date" name="invoice_date" value="{{ old('invoice_date', now()->format('Y-m-d')) }}" required></div><div class="mb-3"><label class="form-label">Vencimiento</label><input class="form-control" type="date" name="due_date" value="{{ old('due_date') }}"></div><div class="mb-3"><label class="form-label">Impuesto (%)</label><input class="form-control" type="number" min="0" max="100" step="0.01" name="tax_rate" value="{{ old('tax_rate', 0) }}"></div><div class="mb-3"><label class="form-label">Descuento</label><input class="form-control" type="number" min="0" step="0.01" name="discount_amount" value="{{ old('discount_amount', 0) }}"></div><div class="mb-3"><label class="form-label">Notas</label><textarea class="form-control" name="notes" rows="3">{{ old('notes') }}</textarea></div><button class="btn btn-primary w-100"><i class="fas fa-save me-1"></i> Crear borrador</button></div></div></div>
        </div>
    </form>
@endsection
